title       = "lw"
baseURL     = "https://lilianweng-cli.tamnd.com/"
description = "Browse Lilian Weng machine learning blog"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/lilianweng-cli"
